# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: server/package-lock.json
      - name: Install server dependencies
        run: npm ci
        working-directory: server
      - name: Run server tests
        run: npm test --if-present
        working-directory: server

  build-client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: client/package-lock.json
      - name: Install client dependencies
        run: npm ci
        working-directory: client
      - name: Build client
        run: npm run build --if-present
        working-directory: client

  publish-gpr:
    needs: [build-server, build-client]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com/
      - name: Install server dependencies
        run: npm ci
        working-directory: server
      - name: Publish server package
        run: npm publish
        working-directory: server
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        continue-on-error: true

